apiVersion: apps/v1
kind: Deployment
metadata:
  name:  fastapi-app
  namespace: test-api-ns
spec:
  selector:
    matchLabels:
      app: fastapi-app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  fastapi-app
    spec:
      containers:
      - name:  fastapi-app
        image:  fastapi-app:v1.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 300m
            memory: 300Mi
        ports:
        - containerPort:  80
        envFrom:
        - secretRef:
            name: fastapi-app-secret
          