apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-service
  namespace: test-api-ns
spec:
  selector:
    app: fastapi-app
  type: ClusterIP
  ports:
  - name: fastapi-app
    protocol: TCP
    port: 80
    targetPort: 80 