name: Build & Deploy api to kind

on:
  push:
    branches: 
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn

      - name: Build Docker image
        run: docker build --no-cache -t fastapi-app:v1.0 .

      - name: Set up Kind Cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: kind

      - name: Load Docker image into Kind
        run: |
          docker images
        
          kind load docker-image fastapi-app:v1.0

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
      
      - name: Deploy to Kind
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Verify deployment
        timeout-minutes: 15  # Increase overall timeout
        run: |
          kubectl wait --for=condition=available --timeout=600s deployment/fastapi-app -n test-api-ns
          POD_NAME=$(kubectl get pods -n test-api-ns -l app=fastapi-app \
            --field-selector=status.phase=Running \
            -o jsonpath="{.items[0].metadata.name}")
          kubectl port-forward pod/$POD_NAME 8080:80 -n test-api-ns &
          sleep 8
          curl -v http://localhost:8080/
          sleep 8
          curl -v http://localhost:8080/about/me/